// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIpHLylNoq2vfc_GajE-KS8kmNakeBzXA',
    appId: '1:475381692973:web:0b69a658e36328b75916a4',
    messagingSenderId: '475381692973',
    projectId: 'super-planner-app-3af40',
    authDomain: 'super-planner-app-3af40.firebaseapp.com',
    storageBucket: 'super-planner-app-3af40.firebasestorage.app',
    measurementId: 'G-FFMMX5QG83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFIHb8E1E4TGW-pT1qG0od8yZTY0AN0mc',
    appId: '1:475381692973:android:28f7c0f72f53c9325916a4',
    messagingSenderId: '475381692973',
    projectId: 'super-planner-app-3af40',
    storageBucket: 'super-planner-app-3af40.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1dOzOzxKmBzP44Pz7RSJWbxcEo9M-QMU',
    appId: '1:475381692973:ios:6f07c5cde44d03945916a4',
    messagingSenderId: '475381692973',
    projectId: 'super-planner-app-3af40',
    storageBucket: 'super-planner-app-3af40.firebasestorage.app',
    iosClientId: '475381692973-2um7rmq7gdfb3gdtmb8r7r0q8nfenp53.apps.googleusercontent.com',
    iosBundleId: 'com.superplanner.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1dOzOzxKmBzP44Pz7RSJWbxcEo9M-QMU',
    appId: '1:475381692973:ios:6f07c5cde44d03945916a4',
    messagingSenderId: '475381692973',
    projectId: 'super-planner-app-3af40',
    storageBucket: 'super-planner-app-3af40.firebasestorage.app',
    iosClientId: '475381692973-2um7rmq7gdfb3gdtmb8r7r0q8nfenp53.apps.googleusercontent.com',
    iosBundleId: 'com.superplanner.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIpHLylNoq2vfc_GajE-KS8kmNakeBzXA',
    appId: '1:475381692973:web:ffde3b40d601452b5916a4',
    messagingSenderId: '475381692973',
    projectId: 'super-planner-app-3af40',
    authDomain: 'super-planner-app-3af40.firebaseapp.com',
    storageBucket: 'super-planner-app-3af40.firebasestorage.app',
    measurementId: 'G-B2NTP38ZLH',
  );
}
