// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCf6FgvjttG6mcI74K1xbL7o7R3ZX9iIU',
    appId: '1:850562549978:web:8f2e98a301caecd92dfde3',
    messagingSenderId: '850562549978',
    projectId: 'my-dairy-2f7e2',
    authDomain: 'my-dairy-2f7e2.firebaseapp.com',
    storageBucket: 'my-dairy-2f7e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCf6FgvjttG6mcI74K1xbL7o7R3ZX9iIU',
    appId: '1:850562549978:android:8f2e98a301caecd92dfde3',
    messagingSenderId: '850562549978',
    projectId: 'my-dairy-2f7e2',
    storageBucket: 'my-dairy-2f7e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCf6FgvjttG6mcI74K1xbL7o7R3ZX9iIU',
    appId: '1:850562549978:ios:8f2e98a301caecd92dfde3',
    messagingSenderId: '850562549978',
    projectId: 'my-dairy-2f7e2',
    storageBucket: 'my-dairy-2f7e2.firebasestorage.app',
    iosBundleId: 'com.vibecalendar.myDairy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCf6FgvjttG6mcI74K1xbL7o7R3ZX9iIU',
    appId: '1:850562549978:ios:8f2e98a301caecd92dfde3',
    messagingSenderId: '850562549978',
    projectId: 'my-dairy-2f7e2',
    storageBucket: 'my-dairy-2f7e2.firebasestorage.app',
    iosBundleId: 'com.vibecalendar.myDairy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCf6FgvjttG6mcI74K1xbL7o7R3ZX9iIU',
    appId: '1:850562549978:web:8f2e98a301caecd92dfde3',
    messagingSenderId: '850562549978',
    projectId: 'my-dairy-2f7e2',
    authDomain: 'my-dairy-2f7e2.firebaseapp.com',
    storageBucket: 'my-dairy-2f7e2.firebasestorage.app',
  );
}
